---
title: "Confounding in two series factorials"
runtime: shiny
output: flexdashboard::flex_dashboard
---

```{r}
library(shiny)
library(conf.design)
library(flexdashboard)

blocks <- function(k, q, x, binaryCol = TRUE, table = FALSE, printset = TRUE)
{
  sick = as.matrix(strsplit(x, ""))
  sickness = do.call(rbind, sick)
  matrix(as.numeric(sickness), nrow = nrow(sickness))
  testgen = matrix(as.numeric(sickness), nrow = nrow(sickness))
  if (q == 1) {
    set = conf.set(testgen, 2)
    str.set = matrix(0, nrow = 1, ncol = 1)
    str.set[1] = paste(set, collapse = "")
  }
  else if (q >= 2) {
    set = conf.set(testgen, 2)
    str.set = matrix(rep(0, nrow(set)), nrow = nrow(set), ncol = 1)
    for (i in 1:nrow(set)) {
      str.set[i] = paste(set[i,], collapse = "")
    }
  }
  if (!q == length(x))
    stop("The number of defining contrasts specified in 'x' is not equal to the number of required contrasts q; check length(x).")
  for(i in 1:length(x)) {
    if(!k == nchar(x[i]))
      stop("At least one binary sequence in 'x' is not equal to the required length k; check nchar(x) == k.")
  }
  ntrt = 2^k
  nblock = 2^q
  input = expand.grid(replicate(k, 0:1, simplify = FALSE))
  str.input = matrix(rep(0, nrow(input)), nrow = nrow(input), ncol = 1)
  for (i in 1:nrow(input)) {
    str.input[i] =  paste(input[i,], collapse = "")
  }
  confounder <- rep(list(NULL), q)
  names(confounder) <- paste("confounder", 1:q, sep = "")
  for (i in 1:q) {
    confounder[[i]] <- x[i]
  }
  len = nchar(confounder[[1]])
  matching <- rep(list(NULL), q)
  names(matching) = paste("match", 1:q, sep = "")
  for (i in 1:q) {
    matching[[i]] =  matrix(rep(rep(3, len), nrow(input)), nrow = nrow(input))
    for (j in 1:(ntrt)) {
      for (b in 1:len) {
        matching[[i]][j, b] = (substr(str.input[j],b,b) == substr(confounder[[i]],b,b))
      }
    }
  }
  for (i in 1:q) {
    matching[[i]] <- matching[[i]][, which(strsplit(x[i], "")[[1]]=="1")]
    matching[[i]] <- as.matrix(apply(matching[[i]], 1, sum))
    matching[[i]] <- matching[[i]] %% 2
  }
  for (i in 1:q) {
    for (m in 1:ntrt) {
      if (matching[[i]][m] == 1) {
        matching[[i]][m] <- "o"
      } 
      else if (matching[[i]][m] == 0) {
        matching[[i]][m] <- "e"
      }
    }
  }
  term <- matrix((rep("", ntrt)), nrow = ntrt)
  term[1] <- "(1)"
  for (i in 1:ntrt) {
    for(j in 1:k) {
      if (substr(str.input[i], j, j) == 1) {
        term[i] <- paste(term[i], letters[j], sep = "")
      }
    }
  }
  block <- rep(list(NULL), nblock)
  names(block) <- paste("block", 1:nblock, sep = "")
  parity = expand.grid(replicate(q, c("e", "o"), simplify = FALSE))
  str.parity = matrix(rep("", nrow(parity)), nrow = nrow(parity), ncol = 1)
  for (i in 1:nrow(parity)) {
    str.parity[i] = paste(as.matrix(parity[i,1:q]), collapse = "")
  }
  constructblock <- cbind(term, str.input)
  for (i in 1:q) {
    constructblock <- cbind(constructblock, matching[[i]])
  }
  if (q == 1) { 
    l = constructblock[,3]
  } else {
    l = apply(subset(constructblock[,3:(2+q)]), 1, paste, collapse = "")
  }
  
  for (i in 1:nblock){
    block[[i]] = which(l == str.parity[[i]])
  }
  blocknumber <- matrix((rep(0, dim(constructblock)[1])), nrow = dim(constructblock)[1])
  for(i in 1:nblock) {
    blocknumber[block[[i]]] <- i
  }
  constructblock <- cbind(constructblock, blocknumber)
  results <- rep(list(NULL), nblock)
  names(results) <- paste(str.parity, "block", sep = "")
  for (i in 1:length(results)) {
    results[[i]] <- constructblock[block[[i]], 1]
  }
  ind <- matrix(rep(0, length(str.set)), nrow = length(str.set))
  for (i in 1:length(str.set)) {
    ind[i] = which(str.set[i] == constructblock[,2])
  }
  confset = constructblock[ind, 1]
  #if (printset == TRUE) {
  #  cat("The confounded set is \n")
  #  cat("{", toupper(as.character(confset)),"}\n")
  # }
  constructblock <- as.data.frame(constructblock)
  if (binaryCol == TRUE) {
    colnames(constructblock) <- c("treatment", "binary trt", 
                                  x, "blocknumber")
  }
  colnames(constructblock) <- c("treatment", "binary trt", 
                                toupper(as.character(constructblock[match(x, constructblock[,2]),1])),
                                "blocknumber")
  if (table == TRUE) {
    print(constructblock)
  }
  results <- as.data.frame(results)
  results <- list(results = results, confset = toupper(as.character(confset)))
}
```



Column {.sidebar}
-----------------------------------------------------------------------
```{r}
fluidPage(
  helpText("Factors are variables with two levels, e.g. a light switch has an on/off"),
  numericInput("k",
               "Number of factors",
               value = 5),
  helpText("Confounders are treatment effects which are indistinguishable from block effects"),
  numericInput("q",
               "Number of Confounders",
               value = 2),
  helpText("Type in confounders using comma delimiters
           with spaces following the commas, e.g. 10101, 11110, 00010)"),
  uiOutput("helptext"),
  textInput("confounder",
            "Defining Relation",
            value = c("10101, 11110"))
)

```


```{r}
output$background <- reactive({
  
"This is a primitive version of an interactive dashboard that showcases the output of a function that I developed to recommend how to assign treatments to blocks. To understand the use cases for the output, visit https://github.com/benjnguyen/Confounded-and-Fractional-Two-Series-Factorial/blob/master/blocksfnvig.pdf"
})

output$helptext <- renderUI({
  helpText("There should be ", input$q, " confounders should be of length", input$k)
})

conf <- reactive({
  unlist(strsplit(input$confounder, ", "))
})

output$blks <- renderDataTable({
    blocks(input$k, input$q, conf())$results
})

output$confset <- renderPrint({
  blocks(input$k, input$q, conf())$confset
})
```


Column
----------------------------------------
```{r}

mainPanel(

      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = "tabs",
                  tabPanel("Treatments assigned to Blocks", dataTableOutput("blks")),
                  tabPanel("Confounded Set", 
                           p("The confonunded set is the set of treatment effects which cannot be distinguished from one another.
                             The confounded set is generated by multiplying each of the treatment effects in the defining relation
                             with each other. It is an iterative process where treatment aliases are discovered and reconsidered
                             by multiplication with the updated known set of confounded variables until all treatment aliases 
                             are exhaustively discovered."),
                           p("The confounded set based on the given defining relation is"),
                           br(),
                           tableOutput("confset")),

          
                  tabPanel("About",
                            h4("User Manual: ", a("Vignette", href=
                                    "https://github.com/benjnguyen/Confounded-and-Fractional-Two-Series-Factorial/blob/master/blocksfnvig.pdf")),                       
                            p("This is a primitive version of an interactive dashboard that showcases the output of a function that I developed to recommend how to assign treatments to blocks. See the user manual for use cases."),
                            br(),
                            h4("Author Information"),
                            p("Benjamin Nguyen"),
                            p("Email: benjnguyen42@gmail.com"),
                            p("Github:", a("https://github.com/benjnguyen/")),
                            br(), br(), br(), br(), br(),
                            p("Copyright @ 2019, All Rights Reserved"))
      )
)
```



